// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"payslip-generation-system/config"
	"payslip-generation-system/config/infra"
	"payslip-generation-system/config/router"
	"payslip-generation-system/internal/handler"
	"payslip-generation-system/internal/repository/auth"
	"payslip-generation-system/internal/repository/tx"
	"payslip-generation-system/internal/usecase"
	"payslip-generation-system/pkg/log"
	"payslip-generation-system/transport"
)

// Injectors from wire.go:

func ServerApp() *transport.HTTP {
	configConfig := config.ProvideConfig()
	logCustom := log.ProvideLogger()
	infraInfra := infra.ProvideInfra(configConfig, logCustom)
	db := infraInfra.DB
	iAuthRepo := auth.ProvideAuthRepo(infraInfra)
	txManager := tx.ProvideTxManager(infraInfra)
	iUsecase := usecase.ProvideUsc(configConfig, logCustom, db, iAuthRepo, txManager)
	handlerHandler := handler.ProvideHandler(configConfig, logCustom, iUsecase)
	route := router.ProvideRoute(configConfig, logCustom, handlerHandler, iUsecase)
	http := transport.ProvideHttp(configConfig, route, logCustom)
	return http
}

// wire.go:

// Config & Logger
var Configs = wire.NewSet(config.ProvideConfig)

var LoggerSet = wire.NewSet(log.ProvideLogger)

// Infra (DB, dsb)
var InfraSet = wire.NewSet(infra.ProvideInfra, wire.FieldsOf(new(*infra.Infra), "DB"))

// Repositories dasar yang di-inject ke usecase
var RepoSet = wire.NewSet(auth.ProvideAuthRepo, tx.ProvideTxManager)

// Domain layer
var InternalDomain = wire.NewSet(
	RepoSet, usecase.ProvideUsc,
)

// Handlers
var Handler = wire.NewSet(handler.ProvideHandler)

// Server (router + transport)
var Server = wire.NewSet(
	Handler, router.ProvideRoute, transport.ProvideHttp,
)
